services:
  - type: web
    name: career-guidance-ai
    runtime: docker
    plan: free
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: "3000"
      - key: ONET_USERNAME
        sync: false
      - key: ONET_PASSWORD
        sync: false
      - key: BLS_API_KEY
        sync: false
      - key: USAJOBS_API_KEY
        sync: false
      - key: USAJOBS_EMAIL
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: "false"
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_PROJECT
        value: career-guidance-ai
